# Generated by Django 2.2.6 on 2019-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
    ]
