# Generated by Django 2.2.6 on 2019-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191024_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
